name: Martin
description: An all-access pass to info regarding Marty Boggs
url: https://martyboggs.github.io
timezone: America/Los_Angeles
repository: martyboggs/martyboggs.github.io
permalink: /:categories/:title
